### PR TITLE
Updated AspNet.Identity.Mongo from 2.0.4 (pre) to 2.0.8 (stable)

### PR DESCRIPTION
**Pull request by albatros2ko**

### CODE REVIEW

**Comment by vkeusebio** [comment]
rebasing

**Comment by g0t4** [comment]
I think the examples should stay as is, the update to 2.0.8 doesn't contribute to the understanding provided by the example.

**Comment by vkeusebio** [comment]
Okay, but the example doesn't build because NuGet is unable to restore the 2.0.4-alpha package.

**Comment by g0t4** [comment]
Ahh, that makes sense, didn't know they yanked the package. Will you remove
the references to EntityFramework? EntityFramework and
Microsoft.AspNet.Identity.EntityFramework

**Pull request closed without merging**
